version: '3.9'

services:
  app:
    build:
      context: app
      dockerfile: Dockerfile
    volumes:
      - ./:/workspace:cached
      - pycache:/workspace/app/__pycache__
      - $HOME/.ssh:/root/.ssh
    command: /bin/sh -c "while sleep 1000; do :; done"
    depends_on:
      - db
    
  db:
    image: mariadb:10.5
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/log:/var/log/mysql
      - ./mysql/init:/docker-entrypoint-initdb.d
    environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: app
        MYSQL_USER: app
        MYSQL_PASSWORD: app
        TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_bin
    
  phpmyadmin:
    image: phpmyadmin:latest
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=db
      - PMA_USER=root
      - PMA_PASSWORD=root
    ports:
       - 2525:80
    volumes:
       - ./phpmyadmin/sessions:/sessions
       
volumes:
  pycache: