version: '3.9'

services:
  bot:
    image: ghcr.io/ichidaisai/discord-bot-2022:main
    build:
      context: app
      dockerfile: Dockerfile
    volumes:
      - type: bind
        source: "./config.yml"
        target: "/app/config.yml"
    
  db:
    image: mariadb:10.5
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/log:/var/log/mysql
      - ./mysql/init:/docker-entrypoint-initdb.d
    environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: app
        MYSQL_USER: app
        MYSQL_PASSWORD: app
        TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_bin
    
  phpmyadmin:
    image: phpmyadmin:latest
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=db
      - PMA_USER=root
      - PMA_PASSWORD=root
    ports:
       - 2525:80
    volumes:
       - ./phpmyadmin/sessions:/sessions